# Generated by Django 4.2.7 on 2023-12-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('field_of_study', models.CharField(max_length=100)),
                ('ac_id', models.CharField(max_length=100)),
                ('rank', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
