# Generated by Django 5.2.4 on 2025-08-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='password_change_status',
        ),
        migrations.AddField(
            model_name='customuser',
            name='cell',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_profile',
            field=models.ImageField(default='media/profile_pic/sysuser.png', upload_to='media/profile_pic'),
        ),
    ]
