# Generated by Django 5.2.4 on 2025-08-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_customuser_otp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='cell',
        ),
        migrations.AddField(
            model_name='customuser',
            name='otp',
            field=models.CharField(default='000', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_change_status',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_profile',
            field=models.ImageField(default='profile_pic/sysuser.png', upload_to='profile_pic'),
        ),
    ]
